name: 'Test against supported Faraday minor versions before v1.0'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        faraday_version: ['0.9.2', '0.10.1', '0.11.0', '0.12.2', '0.13.1', '0.14.0', '0.15.4', '0.16.2', '0.17.5']
    env:
      FARADAY_VERSION: ~> ${{ matrix.faraday_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.6
      - name: Install dependencies
        run: bundle install
      - name: Run RSpec tests
        run: bundle exec rspec